server:
  port: 9080
spring:
  jpa:
    properties:
      dialect:  org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_skills
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pass4post
    hikari:
      maximum-pool-size: 2
